### ISSUE TITLE
util/walk/PathWalker

### ISSUE THREAD

**Issue by drrob1** [peter-mount/go-kernel#1]
I have a code block that I want to walk my home directory.  I'm getting an error that's stopping the walk.
err = walker.Walk(rootDir)
Error is: open /home/rob/.dbus : permission denied.

I don't want the walk operation to abort when it gets an error like this.  How can I have it continue to completion, ignoring these errors?
The full pgm is here:
    https://go.dev/play/p/BN8rtknwFvA

**Comment by peter-mount** [comment]
This is now fixed in the development branch.

As long as you have permissions to access the root directory, when it encounters a directory and it's unable to scan it due to permissions it now skips that directory.
